---
- hosts: localhost
  become: true
  tasks:
    - name: Install EPEL repository
      dnf:
        name: epel-release
        state: present
      become: true

    - name: Enable crb-devel repository
      dnf:
        name: "https://cdn.redhat.com/content/dist/rhel8/$releasever/x86_64/crb-devel/crb-devel.repo"
        state: present
      become: true

    - name: Install required packages
      dnf:
        name:
          - procps-ng
          - which
          - findutils
          - mlocate
          - the_silver_searcher
          - htop
          - nvtop
          - bison
          - flex
          - wget
          - git
          - python3
          - python3-devel
          - patch
          - giflib-devel
          - libmng
          - libtiff-devel
          - libjpeg-devel
          - libatomic
          - libuuid-devel
          - openssl-devel
          - curl-devel
          - blosc
          - blosc-devel
          - boost
          - boost-*
          - lua
          - lua-libs
          - lua-devel
          - openvdb
          - openvdb-libs
          - openvdb-devel
          - tbb
          - tbb-devel
          - python3-tbb
          - log4cplus
          - log4cplus-devel
          - cppunit
          - cppunit-devel
          - doxygen
          - graphviz
          - python3-docutils
          - glfw
          - glfw-devel
          - compat-libpthread-nonshared
          - python3-jinja2
          - python3-pygments
          - glew
          - glew-devel
          - libGLEW
          - freeglut
          - freeglut-devel
          - expat
          - expat-devel
          - lua-expat
          - yaml-cpp
          - yaml-cpp-devel
          - pystring
          - pystring-devel
          - lcms2
          - lcms2-utils
          - lcms2-devel
          - pybind11-devel
          - python3-pybind11
          - onednn
          - onednn-devel
          - zlib
          - zlib-devel
          - redhat-lsb-core
          - perl-English
        state: present
      become: true

    - name: Add Nvidia CUDA repository
      dnf_repository:
        name: cuda-rhel9
        description: Nvidia CUDA repository for RHEL 9
        baseurl: https://developer.download.nvidia.com/compute/cuda/repos/rhel9/x86_64/
        enabled: true
        gpgcheck: true
        gpgkey: https://developer.download.nvidia.com/compute/cuda/repos/rhel9/x86_64/7fa2af80.pub
      become: true

    - name: Install CUDA
      dnf:
        name:
          - cuda-runtime-11-8
          - cuda-toolkit-11-8
        state: present
      become: true

    - name: Install clang and clang-devel
      dnf:
        name:
          - clang
          - clang-devel
        state: present
      become: true

  - name: Create /installs directory and subdirectories
    file:
      path: "{{ item.path }}"
      state: directory
      mode: '0755'
    loop:
      - { path: /installs }
      - { path: /installs/bin }
      - { path: /installs/lib }
      - { path: /installs/include }
     
     - name: Change directory to /installs
      become: true
      command: cd /installs

    - name: Download CMake archive
      become: true
      get_url:
        url: https://github.com/Kitware/CMake/releases/download/v3.23.1/cmake-3.23.1-linux-x86_64.tar.gz
        dest: /installs/cmake-3.23.1-linux-x86_64.tar.gz

    - name: Extract CMake archive
      become: true
      unarchive:
        src: /installs/cmake-3.23.1-linux-x86_64.tar.gz
        dest: /installs/
        remote_src: yes

    - name: Create source directory
      file:
        path: /source
        state: directory
        mode: 0755

    - name: Change directory to /source
      become: true
      shell: cd /source

    - name: Clone openmoonray repository
      become: true
      git:
        repo: https://github.com/dreamworksanimation/openmoonray.git
        dest: /source/openmoonray
        recursive: true
