---
- name: Base build to prep OS for dependancy builds
  hosts: localhost
  become: true
  environment:
    PATH: "{{ ansible_env.PATH }}:/installs/cmake-3.23.1-linux-x86_64/bin"
  tasks:
    - name: Install EPEL repository
      dnf:
        name: epel-release
        state: present

    - name: Install CRB devel repository
      command: dnf config-manager --enable crb devel

    - name: Install required packages
      dnf:
        name: "{{ item }}"
        state: present
      loop:
        - procps-ng
        - which
        - findutils
        - mlocate
        - the_silver_searcher
        - htop
        - nvtop
        - bison
        - flex
        - wget
        - git
        - python3
        - python3-devel
        - patch
        - giflib-devel
        - libmng
        - libtiff-devel
        - libjpeg-devel
        - libatomic
        - libuuid-devel
        - openssl-devel
        - curl-devel
        - blosc
        - blosc-devel
        - boost
        - boost-*
        - lua
        - lua-libs
        - lua-devel
        - openvdb
        - openvdb-libs
        - openvdb-devel
        - tbb
        - tbb-devel
        - python3-tbb
        - log4cplus
        - log4cplus-devel
        - cppunit
        - cppunit-devel
        - doxygen
        - graphviz
        - python3-docutils
        - glfw
        - glfw-devel
        - compat-libpthread-nonshared
        - python3-jinja2
        - python3-pygments
        - glew
        - glew-devel
        - libGLEW
        - freeglut
        - freeglut-devel
        - expat
        - expat-devel
        - lua-expat
        - yaml-cpp
        - yaml-cpp-devel
        - pystring
        - pystring-devel
        - lcms2
        - lcms2-utils
        - lcms2-devel
        - pybind11-devel
        - python3-pybind11
        - onednn
        - onednn-devel
        - zlib
        - zlib-devel
        - redhat-lsb-core
        - perl-English
        
#    - name: Add Nvidia CUDA repository
#      yum_repository:
#        name: cuda-rhel9
#        description: Nvidia CUDA repository for RHEL 9
#        baseurl: https://developer.download.nvidia.com/compute/cuda/repos/rhel9/x86_64/
#        enabled: true
#        gpgcheck: true
#        gpgkey: https://developer.download.nvidia.com/compute/cuda/repos/rhel9/x86_64/7fa2af80.pub

#    - name: Install CUDA
#      dnf:
#        name:
#          - cuda-runtime-11-8
#          - cuda-toolkit-11-8
#        state: present

    - name: Install clang and clang-devel
      dnf:
        name:
          - clang
          - clang-devel
        state: present

    - name: Create /installs directory and subdirectories
      file:
        path: "{{ item.path }}"
        state: directory
        mode: '0755'
      loop:
        - { path: /installs }
        - { path: /installs/bin }
        - { path: /installs/lib }
        - { path: /installs/include }
     
    - name: Change directory to /installs
      command: cd /installs

    - name: Download CMake archive
      get_url:
        url: https://github.com/Kitware/CMake/releases/download/v3.23.1/cmake-3.23.1-linux-x86_64.tar.gz
        dest: /installs/cmake-3.23.1-linux-x86_64.tar.gz

    - name: Extract CMake archive
      unarchive:
        src: /installs/cmake-3.23.1-linux-x86_64.tar.gz
        dest: /installs/
        remote_src: yes

    - name: Create source directory
      file:
        path: /source
        state: directory
        mode: 0755

    - name: Clone openmoonray repository
      git:
        repo: https://github.com/dreamworksanimation/openmoonray.git
        dest: /source/openmoonray
        recursive: true
