---
- name: Step3 - Build Open MoonRay
  hosts: localhost
  become: yes
  tasks:
    - name: Create symbolic link
      file:
        src: /source/openmoonray
        dest: /openmoonray
        state: link
    
    - name: Create directory
      file:
        path: /installs/openmoonray
        state: directory
        mode: 0755
    
    - name: Remove contents of directory
      file:
        path: /build/*
        state: absent
      
    - name: Update CMakeLists
      lineinfile:
        path: "{{ item.path }}"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { path: "/openmoonray/moonray/hydra/CMakeLists.txt", regexp: "^python", line: "python39" }
        - { path: "/openmoonray/moonray/hydra/hdMoonray/CMakeLists.txt", regexp: "^python", line: "python39" }
        - { path: "/openmoonray/moonray/moonshine_usd/CMakeLists.txt", regexp: "^python", line: "python39" }
        - { path: "/openmoonray/moonray/scene_rdl2/mod/python/py_scene_rdl2/CMakeLists.txt", regexp: "^python", line: "python39", insertafter: "10" }
        - { path: "/openmoonray/moonray/hydra/hdMoonray/cmd/hd_cmd/hd_render/CMakeLists.txt", regexp: "Boost::python", line: "Boost::python39" }
        - { path: "/openmoonray/moonray/hydra/hdMoonray/cmd/hd_cmd/hd_usd2rdl/CMakeLists.txt", regexp: "Boost::python", line: "Boost::python39" }
        - { path: "/openmoonray/moonray/scene_rdl2/mod/python/py_scene_rdl2/CMakeLists.txt", regexp: "Boost::python", line: "Boost::python39" }
    
 #   - name: Update _GLIBCXX_USE_CXX11_ABI
 #     shell: ag -l _GLIBCXX_USE_CXX11 . | xargs -n1 sed -i 's/_GLIBCXX_USE_CXX11_ABI=0/_GLIBCXX_USE_CXX11_ABI=1/' $1
 #     args: 
 #       chdir: /openmoonray
        
#    - name: Remove --werror
#      shell: ag -l "\-\-werror" . | grep .cmake | xargs -n1 sed -i 's/--werror/#--werror/' $1
#      args: 
#        chdir: /openmoonray
      
#    - name: Remove env.DWAForceWarningAsError
#      shell: ag -l env.DWAForceWarningAsError | xargs -n1 sed -i 's/env.DWAForceWarningAsError/#env.DWAForceWarningAsError/' $1
#      args: 
#        chdir: /openmoonray  

    - name: Download libcgroup packages
      get_url:
        url: "http://ftp.riken.jp/Linux/centos/7/os/x86_64/Packages/{{ item }}"
        dest: "/installs/{{ item }}"
      with_items:
        - "libcgroup-0.41-21.el7.x86_64.rpm"
        - "libcgroup-devel-0.41-21.el7.x86_64.rpm"

    - name: Install libcgroup packages
      dnf:
        name: "/installs/{{ item }}"
        state: present
        disable_gpg_check: true
      with_items:
        - "libcgroup-0.41-21.el7.x86_64.rpm"
        - "libcgroup-devel-0.41-21.el7.x86_64.rpm"
      
    - name: Create symbolic links
      file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      with_items:
        - { src: "/usr/bin/python3", dest: "/usr/bin/python" }
        - { src: "/usr/lib64/libatomic.so.1", dest: "/usr/lib64/libatomic.so" }
        
    - name: Add #include <array> to BsdfHairOneSampler.h
      lineinfile:
        path: "moonray/moonray/lib/rendering/shading/bsdf/hair/BsdfHairOneSampler.h"
        insertafter: "BsdfHairLobes.h"
        line: "#include <array>"

    - name: Add #include <array> to Worley.h
      lineinfile:
        path: "moonray/moonshine/lib/common/noise/Worley.h"
        insertafter: "Color.h"
        line: "#include <array>"

    - name: Add #include <string> to MsgSendHandler.h
      lineinfile:
        path: "moonray/moonray_arras/mcrt_dataio/lib/engine/merger/MsgSendHandler.h"
        insertafter: "#include <functional>"
        line: "#include <string>"

    - name: Add #include <array> to GPUPrimitive.h
      lineinfile:
        path: "moonray/moonray/lib/rendering/rt/gpu/GPUPrimitive.h"
        insertafter: "#include <vector>"
        line: "#include <array>"

    - name: Replace #include <float.h> with #include <limits> in RenderTimingRecord.h
      lineinfile:
        path: "moonray/moonray/lib/rendering/rndr/RenderTimingRecord.h"
        regexp: "#include <float\.h>"
        line: "#include <limits>"

    - name: Add #include <shared_mutex> and replace it with #include <mutex> in ReaderWriterMutex.h
      lineinfile:
        path: "moonray/scene_rdl2/include/scene_rdl2/render/util/ReaderWriterMutex.h"
        insertafter: "#pragma once"
        line: "#include <shared_mutex>"
      lineinfile:
        path: "moonray/scene_rdl2/include/scene_rdl2/render/util/ReaderWriterMutex.h"
        regexp: "#include <shared_mutex>"
        line: "#include <mutex>"

    - name: Add #include <functional> to McrtUpdate.h
      lineinfile:
        path: "moonray/moonray_arras/mcrt_computation/lib/engine/mcrt/McrtUpdate.h"
        insertafter: "#pragma once"
        line: "#include <functional>"
