- name: Build depenancies
  hosts: localhost
  become: true
  environment:
    PATH: "{{ ansible_env.PATH }}:/installs/cmake-3.23.1-linux-x86_64/bin"
  tasks:
    - name: Create symbolic link
      file:
        src: /source/openmoonray/building
        dest: /building
        state: link
        force: yes
        
    - name: Create directory
      file:
        path: /build
        state: directory
        mode: '0755'
        
    - name: Clone jsoncpp repository
      git:
        repo: https://github.com/open-source-parsers/jsoncpp.git
        dest: /build/jsoncpp
        version: 0.10.7
        
    - name: Create directory
      file:
        path: /build/jsoncpp/build
        state: directory
        mode: '0755'

    - name: Create JsonCpp build directory
      file:
        path: /build/jsoncpp/build
        state: directory
        mode: '0755'

    - name: Configure jsoncpp
      shell: CC=clang CXX=clang++ cmake -DCMAKE_INSTALL_PREFIX:PATH=/installs -DBUILD_SHARED_LIBS=1 -DJSONCPP_LIB_BUILD_SHARED=1 -DPYTHON_EXECUTABLE=/usr/bin/python3 ..
      args:
        chdir: /build/jsoncpp/build

    - name: Compile jsoncpp
      make:
        chdir: /build/jsoncpp/build
        target: install
 
    - name: Create libmicrohttpd build directory
      file:
        path: /build/libmicrohttpd
        state: directory
        mode: '0755' 
 
    - name: Download libmicrohttpd
      get_url:
        url: https://ftp.gnu.org/gnu/libmicrohttpd/libmicrohttpd-0.9.37.tar.gz
        dest: /build/libmicrohttpd/libmicrohttpd-0.9.37.tar.gz

    - name: Extract libmicrohttpd
      unarchive:
        src: /build/libmicrohttpd/libmicrohttpd-0.9.37.tar.gz
        dest: /build/libmicrohttpd
        remote_src: true
        extra_opts: [--strip-components=1]

    - name: Configure libmicrohttpd
      shell: CC=clang CXX=clang++ ./configure --prefix=/installs
      args:
        chdir: /build/libmicrohttpd

    - name: Compile libmicrohttpd
      make:
        chdir: /build/libmicrohttpd
        target: install

## Build OpenSubdiv        
    - name: Create OpenSubdiv build directory
      file:
        path: /build/OpenSubdiv
        state: directory
        mode: '0755' 
 
    - name: Clone OpenSubdiv repository
      git:
        repo: https://github.com/PixarAnimationStudios/OpenSubdiv
        dest: /build/OpenSubdiv
        
    - name: Create OpenSubdiv build directory
      file:
        path: /build/OpenSubdiv/build
        state: directory
        mode: '0755'
    ## turned off cuda and gltests
    - name: Configure OpenSubdiv
      shell: CC=clang CXX=clang++ cmake -DCMAKE_INSTALL_PREFIX:PATH=/installs -DCMAKE_BUILD_TYPE=Release -DNO_PTEX=1 -DNO_OMP=1 -DNO_TBB=1 -DNO_CUDA=0 -DNO_GLFW_X11=1 -DNO_OPENCL=1 -DNO_CLEW=1 -DNO_REGRESSION=1 -DNO_EXAMPLES=1 -DNO_TUTORIALS=1 -DNO_DOC=1 -DNO_GLTESTS=0 -DNO_MACOS_FRAMEWORK=1 -DNO_METAL=1 -DNO_TESTS=1 -DPYTHON_EXECUTABLE=/usr/bin/python3 ..
      args:
        chdir: /build/OpenSubdiv/build

    - name: Compile OpenSubdiv
      make:
        chdir: /build/OpenSubdiv/build
        target: install
        
## Build Random123        
    - name: Create Random123 build directory
      file:
        path: /build/Random123
        state: directory
        mode: '0755' 
 
    - name: Clone Random123 repository
      git:
        repo: https://github.com/DEShawResearch/random123.git
        dest: /build/random123
        version: "726a093cd9a73f3ec3c8d7a70ff10ed8efec8d13"

    - name: Install Random123 headers
      command: make install-include prefix=/installs
      args:
        chdir: /build/random123
