- name: Build depenancies
  hosts: localhost
  become: true
  environment:
    PATH: "{{ ansible_env.PATH }}:/installs/cmake-3.23.1-linux-x86_64/bin"
  tasks:
    - name: Create symbolic link
      file:
        src: /source/openmoonray/building
        dest: /building
        state: link
        force: yes
        
    - name: Create directory
      file:
        path: /build
        state: directory
        mode: '0755'
        
    - name: Clone jsoncpp repository
      git:
        repo: https://github.com/open-source-parsers/jsoncpp.git
        dest: /build/jsoncpp
        version: 0.10.7
        
    - name: Create directory
      file:
        path: /build/jsoncpp/build
        state: directory
        mode: '0755'

    - name: Create JsonCpp build directory
      file:
        path: /build/jsoncpp/build
        state: directory
        mode: '0755'

    - name: Configure jsoncpp
      shell: CC=clang CXX=clang++ cmake -DCMAKE_INSTALL_PREFIX:PATH=/installs -DBUILD_SHARED_LIBS=1 -DJSONCPP_LIB_BUILD_SHARED=1 -DPYTHON_EXECUTABLE=/usr/bin/python3 ..
      args:
        chdir: /build/jsoncpp/build

    - name: Compile jsoncpp
      make:
        chdir: /build/jsoncpp/build
        target: install
 
    - name: Create libmicrohttpd build directory
      file:
        path: /build/libmicrohttpd
        state: directory
        mode: '0755' 
 
    - name: Download libmicrohttpd
      get_url:
        url: https://ftp.gnu.org/gnu/libmicrohttpd/libmicrohttpd-0.9.37.tar.gz
        dest: /build/libmicrohttpd/libmicrohttpd-0.9.37.tar.gz

    - name: Extract libmicrohttpd
      unarchive:
        src: /build/libmicrohttpd-0.9.37.tar.gz
        dest: /build/libmicrohttpd
        remote_src: true
        extra_opts: [--strip-components=1]

    - name: Configure libmicrohttpd
      command: CC=clang CXX=clang++ ./configure --prefix=/installs
      args:
        chdir: /build/libmicrohttpd

    - name: Compile libmicrohttpd
      make:
        chdir: /build/libmicrohttpd
        target: install
